// Original SVG exports from the approved Figma file, stored locally.
export const figmaAssets = {
  dashboard: {
    imgIconShield: "/figma/dashboard-imgIconShield.svg",
    imgIconDashboard: "/figma/dashboard-imgIconDashboard.svg",
    imgIconTransactions: "/figma/dashboard-imgIconTransactions.svg",
    imgIconMembers: "/figma/dashboard-imgIconMembers.svg",
    imgIconSettings: "/figma/dashboard-imgIconSettings.svg",
    imgIconShield1: "/figma/dashboard-imgIconShield1.svg",
    imgIconClock: "/figma/dashboard-imgIconClock.svg",
  },
  review: {
    imgIconShield: "/figma/review-imgIconShield.svg",
    imgIconDashboard: "/figma/review-imgIconDashboard.svg",
    imgIconTransactions: "/figma/review-imgIconTransactions.svg",
    imgIconMembers: "/figma/review-imgIconMembers.svg",
    imgIconSettings: "/figma/review-imgIconSettings.svg",
    imgIconShield1: "/figma/review-imgIconShield1.svg",
    imgIconShield2: "/figma/review-imgIconShield2.svg",
    imgIconCheck: "/figma/review-imgIconCheck.svg",
    imgIconCheck1: "/figma/review-imgIconCheck1.svg",
    imgIconClock: "/figma/review-imgIconClock.svg",
  },
  settings: {
    imgIconShield: "/figma/settings-imgIconShield.svg",
    imgIconDashboard: "/figma/settings-imgIconDashboard.svg",
    imgIconTransactions: "/figma/settings-imgIconTransactions.svg",
    imgIconMembers: "/figma/settings-imgIconMembers.svg",
    imgIconSettings: "/figma/settings-imgIconSettings.svg",
    imgIconShield1: "/figma/settings-imgIconShield1.svg",
  },
  members: {
    imgIconShield: "/figma/members-imgIconShield.svg",
    imgIconDashboard: "/figma/members-imgIconDashboard.svg",
    imgIconTransactions: "/figma/members-imgIconTransactions.svg",
    imgIconMembers: "/figma/members-imgIconMembers.svg",
    imgIconSettings: "/figma/members-imgIconSettings.svg",
    imgIconShield1: "/figma/members-imgIconShield1.svg",
    imgIconMembers1: "/figma/members-imgIconMembers1.svg",
    imgIconShield2: "/figma/members-imgIconShield2.svg",
  },
  initiate: {
    imgIconClose: "/figma/initiate-imgIconClose.svg",
  },
  trades: {
    imgIconShield: "/figma/trades-imgIconShield.svg",
    imgIconDashboard: "/figma/trades-imgIconDashboard.svg",
    imgIconTransactions: "/figma/trades-imgIconTransactions.svg",
    imgIconMembers: "/figma/trades-imgIconMembers.svg",
    imgIconSettings: "/figma/trades-imgIconSettings.svg",
    imgIconShield1: "/figma/trades-imgIconShield1.svg",
  },
  decoding: {
    imgIconShield: "/figma/decoding-imgIconShield.svg",
    imgIconDashboard: "/figma/decoding-imgIconDashboard.svg",
    imgIconTransactions: "/figma/decoding-imgIconTransactions.svg",
    imgIconMembers: "/figma/decoding-imgIconMembers.svg",
    imgIconSettings: "/figma/decoding-imgIconSettings.svg",
    imgIconShield1: "/figma/decoding-imgIconShield1.svg",
    imgIconScan: "/figma/decoding-imgIconScan.svg",
    imgIconCheck: "/figma/decoding-imgIconCheck.svg",
    imgIconClock: "/figma/decoding-imgIconClock.svg",
    imgIconClock1: "/figma/decoding-imgIconClock1.svg",
  },
  blocked: {
    imgIconShield: "/figma/blocked-imgIconShield.svg",
    imgIconDashboard: "/figma/blocked-imgIconDashboard.svg",
    imgIconTransactions: "/figma/blocked-imgIconTransactions.svg",
    imgIconMembers: "/figma/blocked-imgIconMembers.svg",
    imgIconSettings: "/figma/blocked-imgIconSettings.svg",
    imgIconShield1: "/figma/blocked-imgIconShield1.svg",
    imgIconShield2: "/figma/blocked-imgIconShield2.svg",
    imgIconShield3: "/figma/blocked-imgIconShield3.svg",
    imgIconClock: "/figma/blocked-imgIconClock.svg",
  },
  missing: {
    imgIconShield: "/figma/missing-imgIconShield.svg",
    imgIconDashboard: "/figma/missing-imgIconDashboard.svg",
    imgIconTransactions: "/figma/missing-imgIconTransactions.svg",
    imgIconMembers: "/figma/missing-imgIconMembers.svg",
    imgIconSettings: "/figma/missing-imgIconSettings.svg",
    imgIconShield1: "/figma/missing-imgIconShield1.svg",
    imgIconShield2: "/figma/missing-imgIconShield2.svg",
    imgIconCheck: "/figma/missing-imgIconCheck.svg",
    imgIconClock: "/figma/missing-imgIconClock.svg",
  },
  unavailable: {
    imgIconShield: "/figma/unavailable-imgIconShield.svg",
    imgIconDashboard: "/figma/unavailable-imgIconDashboard.svg",
    imgIconTransactions: "/figma/unavailable-imgIconTransactions.svg",
    imgIconMembers: "/figma/unavailable-imgIconMembers.svg",
    imgIconSettings: "/figma/unavailable-imgIconSettings.svg",
    imgIconShield1: "/figma/unavailable-imgIconShield1.svg",
    imgIconScan: "/figma/unavailable-imgIconScan.svg",
    imgIconClock: "/figma/unavailable-imgIconClock.svg",
    imgIconClock1: "/figma/unavailable-imgIconClock1.svg",
    imgIconClock2: "/figma/unavailable-imgIconClock2.svg",
  },
  transactions: {
    imgIconShield: "/figma/transactions-imgIconShield.svg",
    imgIconDashboard: "/figma/transactions-imgIconDashboard.svg",
    imgIconTransactions: "/figma/transactions-imgIconTransactions.svg",
    imgIconMembers: "/figma/transactions-imgIconMembers.svg",
    imgIconSettings: "/figma/transactions-imgIconSettings.svg",
    imgIconShield1: "/figma/transactions-imgIconShield1.svg",
  },
  ready: {
    imgIconShield: "/figma/ready-imgIconShield.svg",
    imgIconDashboard: "/figma/ready-imgIconDashboard.svg",
    imgIconTransactions: "/figma/ready-imgIconTransactions.svg",
    imgIconMembers: "/figma/ready-imgIconMembers.svg",
    imgIconSettings: "/figma/ready-imgIconSettings.svg",
    imgIconShield1: "/figma/ready-imgIconShield1.svg",
    imgIconShield2: "/figma/ready-imgIconShield2.svg",
    imgIconCheck: "/figma/ready-imgIconCheck.svg",
    imgIconCheck1: "/figma/ready-imgIconCheck1.svg",
  },
  executed: {
    imgIconShield: "/figma/executed-imgIconShield.svg",
    imgIconDashboard: "/figma/executed-imgIconDashboard.svg",
    imgIconTransactions: "/figma/executed-imgIconTransactions.svg",
    imgIconMembers: "/figma/executed-imgIconMembers.svg",
    imgIconSettings: "/figma/executed-imgIconSettings.svg",
    imgIconShield1: "/figma/executed-imgIconShield1.svg",
    imgIconShield2: "/figma/executed-imgIconShield2.svg",
    imgIconCheck: "/figma/executed-imgIconCheck.svg",
    imgIconCheck1: "/figma/executed-imgIconCheck1.svg",
  },
  settled: {
    imgIconShield: "/figma/settled-imgIconShield.svg",
    imgIconDashboard: "/figma/settled-imgIconDashboard.svg",
    imgIconTransactions: "/figma/settled-imgIconTransactions.svg",
    imgIconMembers: "/figma/settled-imgIconMembers.svg",
    imgIconSettings: "/figma/settled-imgIconSettings.svg",
    imgIconShield1: "/figma/settled-imgIconShield1.svg",
    imgIconShield2: "/figma/settled-imgIconShield2.svg",
    imgIconCheck: "/figma/settled-imgIconCheck.svg",
    imgIconCheck1: "/figma/settled-imgIconCheck1.svg",
  },
  status: {
    imgIconClose: "/figma/status-imgIconClose.svg",
  },
  states: {
    imgIconShield: "/figma/states-imgIconShield.svg",
    imgIconDashboard: "/figma/states-imgIconDashboard.svg",
    imgIconTransactions: "/figma/states-imgIconTransactions.svg",
    imgIconMembers: "/figma/states-imgIconMembers.svg",
    imgIconSettings: "/figma/states-imgIconSettings.svg",
    imgIconShield1: "/figma/states-imgIconShield1.svg",
  },
  receive: {
    imgIconClose: "/figma/receive-imgIconClose.svg",
  },
} as const;
